apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: development-team
spec:
  selector:
    matchLabels:
      app: hotels
  replicas: 2
  template:
    metadata:
      labels:
        app: hotels
    spec:
      serviceAccountName: tripdeal
      containers:
      - image: mahmoud94/sample-nodejs-api:v1.6
        name: hotels
        ports:
        - containerPort: 8080